#!/usr/bin/env python

Import("env")
Import("env_modules")

env_zmq = env_modules.Clone()

# Thirdparty source files

thirdparty_obj = []

# if env["builtin_zmq"]:
thirdparty_dir = "#thirdparty/zmqpp/"
thirdparty_sources = [
    "actor.cpp",
    "auth.cpp",
    "context.cpp",
    "curve.cpp",
    "frame.cpp",
    "loop.cpp",
    "message.cpp",
    "poller.cpp",
    "proxy.cpp",
    "proxy_steerable.cpp",
    "reactor.cpp",
    "signal.cpp",
    "socket.cpp",
    "z85.cpp",
    "zap_request.cpp",
    "zmqpp.cpp"
]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_zmq.Prepend(CPPPATH=[thirdparty_dir])
# env_enet.Append(CPPDEFINES=["GODOT_ENET"])

env_thirdparty = env_zmq.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj


# Godot source files

module_obj = []

env_zmq.add_source_files(module_obj, "*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
